### ISSUE TITLE
Make the Cards in the /sheets screen buttons

### ISSUE THREAD

**Issue by samarth-ramesh** [samarth-ramesh/timetracker-frontend#2]
### Objective:

Transform the cards in the /Sheets screen into buttons, replacing the current implementation that relies on div elements and onClick handlers. Additionally, ensure that the Sheets screen becomes keyboard-navigable for enhanced accessibility.

### Specifications:

1. **Card-to-Button Transformation:**
   - Replace the existing div elements used for cards with button elements.

2. **Button Appearance:**
   - Style the buttons to maintain the visual design consistency of the cards. This may include background colors, borders, and typography.

3. **Accessibility:**
   - Implement appropriate ARIA (Accessible Rich Internet Applications) attributes to ensure the buttons are fully accessible to screen readers and assistive technologies.

4. **Keyboard Navigation:**
   - Ensure that users can navigate through the buttons using keyboard controls.
     - Users should be able to use the "Tab" key to move between buttons.
     - Users should be able to activate the currently focused button by pressing the "Enter" key.
     - Ensure a clear visual indicator (e.g., focus ring) for the active button.
     
5. **Focus Management:**
   - Implement focus management to prevent users from getting trapped in the buttons loop.
     - When the last button is focused and the user presses "Tab," focus should move to the next interactive element (e.g., links or form inputs).

6. **OnClick Functionality:**
   - If the cards had onClick functionality, ensure that this functionality is preserved when the buttons are clicked.

7. **Testing and QA:**
   - Thoroughly test the button implementation to ensure that it performs equivalently to the previous div-based cards.
   - Verify that keyboard navigation works as expected.

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by shreyahegde26** [comment]
Can i get assigned to this?

**Comment by RishavSinha20** [comment]
can i get assigned to this?

**Comment by siri-n-shetty** [comment]
can i get assigned?

**Comment by SmritiMallya** [comment]
can I get assigned?

**Comment by PandaTGOS** [comment]
@samarth-ramesh I am still working on this can I get a little more time ?

**Comment by samarth-ramesh** [comment]
Ok

**Comment by samarth-ramesh** [comment]
@shreyahegde26 assigning to you

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by samarth-ramesh** [comment]
ok @ssether04

**Comment by akshatnavlani** [comment]
Can I get assigned to the issue if it is still not solved @samarth-ramesh

**Comment by samarth-ramesh** [comment]
OK, Akshat, issue is yours

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by akshatnavlani** [comment]
Can I start the work after the performance.

**Comment by samarth-ramesh** [comment]
ok

**Comment by akshatnavlani** [comment]
I want to start the work but i am unable to access the sheets file manually also I don't know the username and password @samarth-ramesh

**Comment by Alley2717** [comment]
can i try

**Comment by samarth-ramesh** [comment]
Sorry, its closed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
