### ISSUE TITLE
Improve error handling in /sheets/{sheet_id} screen

### ISSUE THREAD

**Issue by samarth-ramesh** [samarth-ramesh/timetracker-frontend#5]
## Objective
Enhance the application to gracefully redirect users to the login screen when no login token is present, preventing crashes caused by unhandled API errors.

## Specifications

1. **Check for Login Token:**
   - Check whether a valid login token exists for the user.

2. **Error Handling:**
   - Implement proper error handling to catch any API errors related to the absence of a login token.

3. **Redirect Logic:**
   - If no login token is found or if an API error related to login token absence occurs, redirect the user to the login screen.

4. **Redirect Mechanism:**
   - Ensure that the redirect mechanism preserves user session data or provides a seamless login experience, such as pre-filling the username or other relevant fields.

5. **Clear Error Messages:**
   - Display clear and user-friendly error messages on the login screen to inform users why they are being redirected.

6. **HTTP Status Codes:**
   - Use appropriate HTTP status codes for the redirects, such as a 302 Found for a temporary redirect.

7. **Testing:**
   - Thoroughly test the error handling and redirect logic to confirm that users are gracefully redirected to the login screen when no login token exists.

**Comment by rithulkamesh** [comment]
Please Assign

**Comment by samarth-ramesh** [comment]
@rithulkamesh go for it

**Comment by rithulkamesh** [comment]
@samarth-ramesh is there a test credential we can use to ping your auth route?

**Comment by rithulkamesh** [comment]
#5

**Comment by rithulkamesh** [comment]
#8

**Comment by samarth-ramesh** [comment]
!bounty 80

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
